name: Integración Continua Maven

on:
  push:
    branches:
      - master

jobs:
  Start_test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - uses: ashley-taylor/junit-report-annotations-action@1.3
      if: always()
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}